// Package parametervalidation provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package parametervalidation

import (
	"encoding"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"regexp"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GetValidatedNumberParamsId.
const (
	N3 GetValidatedNumberParamsId = 3
	N5 GetValidatedNumberParamsId = 5
)

// Valid indicates whether the value is a known member of the GetValidatedNumberParamsId enum.
func (e GetValidatedNumberParamsId) Valid() bool {
	switch e {
	case N3:
		return true
	case N5:
		return true
	default:
		return false
	}
}

// Defines values for GetValidatedStringParamsName.
const (
	Abc  GetValidatedStringParamsName = "abc"
	Abcd GetValidatedStringParamsName = "abcd"
)

// Valid indicates whether the value is a known member of the GetValidatedStringParamsName enum.
func (e GetValidatedStringParamsName) Valid() bool {
	switch e {
	case Abc:
		return true
	case Abcd:
		return true
	default:
		return false
	}
}

// GetCustomParams defines parameters for GetCustom.
type GetCustomParams struct {
	Code CustomCode `form:"code" json:"code"`
}

// GetValidatedNumberParamsId defines parameters for GetValidatedNumber.
type GetValidatedNumberParamsId int

// GetValidatedStringParams defines parameters for GetValidatedString.
type GetValidatedStringParams struct {
	Name GetValidatedStringParamsName `form:"name" json:"name"`
}

// GetValidatedStringParamsName defines parameters for GetValidatedString.
type GetValidatedStringParamsName string

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /custom)
	GetCustom(w http.ResponseWriter, r *http.Request, params GetCustomParams)

	// (GET /validated-number/{id})
	GetValidatedNumber(w http.ResponseWriter, r *http.Request, id GetValidatedNumberParamsId)

	// (GET /validated-string)
	GetValidatedString(w http.ResponseWriter, r *http.Request, params GetValidatedStringParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /custom)
func (_ Unimplemented) GetCustom(w http.ResponseWriter, r *http.Request, params GetCustomParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /validated-number/{id})
func (_ Unimplemented) GetValidatedNumber(w http.ResponseWriter, r *http.Request, id GetValidatedNumberParamsId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /validated-string)
func (_ Unimplemented) GetValidatedString(w http.ResponseWriter, r *http.Request, params GetValidatedStringParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCustom operation middleware
func (siw *ServerInterfaceWrapper) GetCustom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomParams

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	err = validateParamCustomType("code", r.URL.Query().Get("code"), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustom(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetValidatedNumber operation middleware
func (siw *ServerInterfaceWrapper) GetValidatedNumber(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id GetValidatedNumberParamsId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	err = validateParamNumber("id", float64(id), 2.000000, true, true, 6.000000, true, false, []float64{3, 5}, true)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetValidatedNumber(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetValidatedString operation middleware
func (siw *ServerInterfaceWrapper) GetValidatedString(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetValidatedStringParams

	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		}
		return
	}

	err = validateParamString("name", string(params.Name), 3, true, 5, true, "^[a-z]+$", true, []string{"abc", "abcd"}, true)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetValidatedString(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/custom", wrapper.GetCustom)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/validated-number/{id}", wrapper.GetValidatedNumber)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/validated-string", wrapper.GetValidatedString)
	})

	return r
}

func validateParamString(paramName string, value string, minLength uint64, hasMinLength bool, maxLength uint64, hasMaxLength bool, pattern string, hasPattern bool, enumValues []string, hasEnum bool) error {
	if hasMinLength && uint64(len([]rune(value))) < minLength {
		return fmt.Errorf("parameter %s length must be at least %d", paramName, minLength)
	}
	if hasMaxLength && uint64(len([]rune(value))) > maxLength {
		return fmt.Errorf("parameter %s length must be at most %d", paramName, maxLength)
	}
	if hasPattern {
		matched, err := regexp.MatchString(pattern, value)
		if err != nil {
			return err
		}
		if !matched {
			return fmt.Errorf("parameter %s must match pattern %q", paramName, pattern)
		}
	}
	if hasEnum {
		for _, enumValue := range enumValues {
			if value == enumValue {
				return nil
			}
		}
		return fmt.Errorf("parameter %s must be one of %v", paramName, enumValues)
	}
	return nil
}

func validateParamNumber(paramName string, value float64, minimum float64, hasMinimum bool, exclusiveMinimum bool, maximum float64, hasMaximum bool, exclusiveMaximum bool, enumValues []float64, hasEnum bool) error {
	if hasMinimum {
		if exclusiveMinimum {
			if !(value > minimum) {
				return fmt.Errorf("parameter %s must be greater than %v", paramName, minimum)
			}
		} else if value < minimum {
			return fmt.Errorf("parameter %s must be greater than or equal to %v", paramName, minimum)
		}
	}
	if hasMaximum {
		if exclusiveMaximum {
			if !(value < maximum) {
				return fmt.Errorf("parameter %s must be less than %v", paramName, maximum)
			}
		} else if value > maximum {
			return fmt.Errorf("parameter %s must be less than or equal to %v", paramName, maximum)
		}
	}
	if hasEnum {
		for _, enumValue := range enumValues {
			if value == enumValue {
				return nil
			}
		}
		return fmt.Errorf("parameter %s must be one of %v", paramName, enumValues)
	}
	return nil
}

func validateParamCustomType(paramName string, value string, dest any) error {
	if tu, ok := dest.(encoding.TextUnmarshaler); ok {
		if err := tu.UnmarshalText([]byte(value)); err != nil {
			return fmt.Errorf("parameter %s: %w", paramName, err)
		}
		return nil
	}
	if ju, ok := dest.(json.Unmarshaler); ok {
		if err := ju.UnmarshalJSON([]byte(value)); err == nil {
			return nil
		}
		quoted, err := json.Marshal(value)
		if err != nil {
			return fmt.Errorf("parameter %s: %w", paramName, err)
		}
		if err := ju.UnmarshalJSON(quoted); err != nil {
			return fmt.Errorf("parameter %s: %w", paramName, err)
		}
	}
	return nil
}
